{
 "title": "Spectrum Virtualize Overview Copy",
 "description": "Dashboard for graphing IBM Spectrum Virtualize (like IBM Flashsystem) using Prometheus as a data source.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(spectrum_temperature, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frontend port load [Bytes/s]",
   "type": "timeseries",
   "description": "Combined port load over nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(spectrum_node_fc_bps{instance=~\"$instance\"}[5m])",
     "legendFormat": "FC node {{id}}"
    },
    {
     "expr": "avg_over_time(spectrum_node_iscsi_bps{instance=~\"$instance\"}[5m])",
     "legendFormat": "iSCSI node {{id}}"
    }
   ]
  },
  {
   "title": "Frontend ports load [IO/s]",
   "type": "timeseries",
   "description": "Combined port load over nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg_over_time(spectrum_node_fc_iops{instance=~\"$instance\"}[5m])",
     "legendFormat": "FC node {{id}}"
    },
    {
     "expr": "avg_over_time(spectrum_node_iscsi_iops{instance=~\"$instance\"}[5m])",
     "legendFormat": "iSCSI node {{id}}"
    }
   ]
  },
  {
   "title": "Backend SAS load [Bytes/s]",
   "type": "timeseries",
   "description": "Backend SAS Load over Nodes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(spectrum_node_sas_bps{instance=~\"$instance\"}[5m])",
     "legendFormat": "Node {{id}}"
    }
   ]
  },
  {
   "title": "Backend SAS load [IO/s]",
   "type": "timeseries",
   "description": "Backend SAS Load over Nodes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg_over_time(spectrum_node_sas_iops{instance=~\"$instance\"}[5m])",
     "legendFormat": "Node {{id}}"
    }
   ]
  },
  {
   "title": "Storage Pool usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "spectrum_pool_used_bytes{instance=~\"$instance\"}/spectrum_pool_capacity_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage Pool free [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "spectrum_pool_free_bytes{instance=~\"$instance\"}/spectrum_pool_capacity_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume per Pool  [#]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spectrum_pool_volume_count{instance=\"$instance\"}",
     "legendFormat": "Name: {{name}}"
    }
   ]
  },
  {
   "title": "Frontend FC-Port load [Bytes/s]",
   "type": "timeseries",
   "description": "Combined port load over nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(spectrum_node_fc_bps{instance=~\"$instance\"}[5m])",
     "legendFormat": "FC node {{id}}"
    }
   ]
  },
  {
   "title": "Load from mdisk  [Bytes/s]",
   "type": "timeseries",
   "description": "Combined port load over nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(spectrum_node_mdisk_read_mb)",
     "legendFormat": "Aggregated read"
    },
    {
     "expr": "sum(spectrum_node_mdisk_write_mb)",
     "legendFormat": "Aggregated write "
    }
   ]
  },
  {
   "title": "Responstime to write to mdisk  [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(spectrum_node_mdisk_read_ms)",
     "legendFormat": "Aggregated mdisk read ms "
    },
    {
     "expr": "avg(spectrum_node_mdisk_write_ms)",
     "legendFormat": "Aggregated mdisk write ms"
    }
   ]
  },
  {
   "title": "Aggregated Volume Responstime  [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(spectrum_node_vdisk_read_ms)",
     "legendFormat": "Aggregated vdisk read ms "
    },
    {
     "expr": "avg(spectrum_node_vdisk_read_ms)",
     "legendFormat": "Aggregated vdisk write ms"
    }
   ]
  },
  {
   "title": "Responstime vdisk  [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(spectrum_node_vdisk_read_ms)",
     "legendFormat": "Aggregated vdisk read ms "
    },
    {
     "expr": "avg(spectrum_node_vdisk_read_ms)",
     "legendFormat": "Aggregated vdisk write ms"
    }
   ]
  },
  {
   "title": "Aggregated Volume  [IO/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(spectrum_node_vdisk_read_iops)",
     "legendFormat": "Aggregated vdisk read IOps "
    },
    {
     "expr": "avg(spectrum_node_vdisk_write_iops)",
     "legendFormat": "Aggregated vdisk write IOps"
    }
   ]
  },
  {
   "title": "Aggregated Volume  [Mb/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(spectrum_node_vdisk_read_mb)",
     "legendFormat": "Aggregated vdisk read "
    },
    {
     "expr": "avg(spectrum_node_vdisk_write_mb)",
     "legendFormat": "Aggregated vdisk write"
    }
   ]
  },
  {
   "title": "CPU usage [%]",
   "type": "timeseries",
   "description": "CPU usage by nodes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "spectrum_node_compression_usage_ratio{instance=~\"$instance\"}",
     "legendFormat": "Compression CPU node {{id}}"
    },
    {
     "expr": "spectrum_node_system_usage_ratio{instance=~\"$instance\"}",
     "legendFormat": "System CPU node {{id}}"
    }
   ]
  },
  {
   "title": "Cache usage [%]",
   "type": "timeseries",
   "description": "Node Cache usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "spectrum_node_write_cache_usage_ratio{instance=~\"$instance\"}",
     "legendFormat": "Write cache node {{id}}"
    },
    {
     "expr": "spectrum_node_total_cache_usage_ratio{instance=~\"$instance\"}",
     "legendFormat": "Total cache node {{id}}"
    }
   ]
  },
  {
   "title": "Enclosure temperature  [C]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "spectrum_temperature{instance=~\"$instance\"}",
     "legendFormat": "Enclosure {{enclosure}}"
    }
   ]
  },
  {
   "title": "Power Usage [W]",
   "type": "timeseries",
   "description": "Power usage by enclosures",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "spectrum_power_watts{instance=~\"$instance\"}",
     "legendFormat": "Enclosure {{enclosure}}"
    }
   ]
  },
  {
   "title": "Health Checker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true
  },
  {
   "title": "PowerSupply status [#]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spectrum_psu_status{status!=\"online\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pool status [#]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spectrum_pool_status{status!=\"online\"})",
     "legendFormat": "Pools Online {{name}}{{status}}"
    }
   ]
  },
  {
   "title": "Drive Status [#]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spectrum_drive_status{status!=\"online\"})",
     "legendFormat": "Drive Status {{name}}{{status}}"
    }
   ]
  },
  {
   "title": "Interfaces FC unexpectedly down [#]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(spectrum_fc_port_status{instance=~\"$instance\",status=\"inactive_configured\"})",
     "legendFormat": "FC"
    }
   ]
  },
  {
   "title": "Interfaces IP unexpectedly down [#]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spectrum_ip_port_state{instance=~\"$instance\",state=\"configured\"} == 1 and on (mac) spectrum_ip_port_link_active{instance=~\"$instance\"} == 0) or vector(0)",
     "legendFormat": "IP"
    }
   ]
  },
  {
   "title": "FC-Port Speed [#]",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spectrum_fc_port_speed_bps",
     "legendFormat": "Node: {{node_id}} - Location: {{adapter_location}} - FC-Port: {{adapter_port_id}}"
    }
   ]
  }
 ]
}